let assessmentStep=1, assessmentDraft={}, historyTab='adherence';
const logoMarkup=`<div class="brand-symbol" aria-hidden="true"><svg viewBox="0 0 56 64" width="48" height="56"><path d="M44 6 Q62 33 43 58" fill="none" stroke="#C9803A" stroke-width="3"/><g fill="currentColor"><rect x="5" y="8" width="26" height="8" rx="4"/><rect x="9" y="21" width="26" height="8" rx="4"/><rect x="13" y="34" width="26" height="8" rx="4"/><rect x="13" y="47" width="26" height="8" rx="4"/></g></svg></div><div><span class="brand-kicker">PROTOCOLO</span><span class="brand-title">Alívio Lombar</span><span class="brand-seal">POR NINE LIVING</span></div>`;
function initializeBrand(){document.documentElement.dataset.theme=localStorage.getItem('care-theme')||'light';document.documentElement.dataset.large=localStorage.getItem('care-large')||'false'}
initializeBrand();
function bindCare(){document.querySelector('.logo').innerHTML=logoMarkup;document.querySelector('.logo').setAttribute('aria-label','Protocolo Alívio Lombar por Nine Living');
const old=document.querySelector('.care-shortcuts');if(old)old.remove();
const dock=document.createElement('aside');dock.className='care-shortcuts';dock.setAttribute('aria-label','Contato, pausa e acessibilidade');dock.innerHTML=`${me?btn('Falar com a equipe','help','secondary')+btn('Pausar','pause-request','secondary'):''}${btn('◐ Tema','theme','secondary')}${btn('A+ Fonte','font','secondary')}`;document.body.append(dock);dock.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action));
app.querySelectorAll('[data-draft]').forEach(el=>el.oninput=()=>assessmentDraft[el.name]=el.value);
}
function careDashboard(){const last=me.sessions[0],count=me.sessions.filter(s=>s.completed).length;const review=me.records.find(r=>r.kind==='review');const plan=me.plan;return `<span class="eyebrow">Hoje</span><div class="row"><h1>Olá, ${esc(me.name.split(' ')[0])}.</h1><span class="pill">${esc(states[me.state])}</span></div><div class="grid"><article class="card highlight"><span class="eyebrow">Seu próximo passo</span><h2>${me.state==='ativo'?'Seu plano de hoje':'Antes de começar'}</h2><p>${me.state==='ativo'?'Preparação, exercícios e fechamento, no seu ritmo.':'Sua equipe revisa a avaliação antes de preparar suas sessões.'}</p>${btn(me.state==='ativo'?'Ver protocolo e aulas':'Preencher minha avaliação',me.state==='ativo'?'protocol':'triage','secondary')}<p class="muted">Os tempos e as doses são sugeridos pelo programa e ajustados pelo profissional.</p></article><aside class="card"><span class="eyebrow">Revisão da equipe</span><h2>${review?'Retorno disponível':'Aguardando'}</h2><p>${review?'Veja a decisão e o motivo registrado pela equipe.':'Suas respostas orientam a próxima revisão profissional.'}</p>${btn('Ver retorno','review','secondary')}</aside></div><div class="cards"><article class="card"><span class="eyebrow">Sua rotina</span><h2>Dia entre sessões</h2><p>Descanso ou atividade leve, conforme sua orientação.</p>${btn('Registrar meu dia','between','secondary')}</article><article class="card"><span class="eyebrow">Acompanhamento</span><h2>${last?.completed&&!last.followup?'Registro pendente':'Meu histórico'}</h2><p>${last?.completed&&!last.followup?'O dia seguinte tem um registro próprio.':'Adesão, resposta e eventos em espaços separados.'}</p>${btn('Abrir histórico','diary','secondary')}</article><article class="card"><span class="eyebrow">Adesão</span><div class="metric">${count}</div><p>${count===1?'Sessão registrada':'Sessões registradas'}</p></article></div>`}
function field(name,label,type='textarea',options=[]){const value=assessmentDraft[name]||'';return `<label for="${name}">${label}</label>${type==='select'?`<select id="${name}" name="${name}" data-draft required><option value="">Selecione</option>${options.map(([v,l])=>`<option value="${v}" ${value===v?'selected':''}>${l}</option>`).join('')}</select>`:`<textarea id="${name}" name="${name}" data-draft maxlength="1000">${esc(value)}</textarea>`}`}
function careTriage(){return `<div class="card form"><div class="row"><span class="eyebrow">Passo ${assessmentStep} de 3</span>${btn('Salvar e sair','assessment-save','secondary')}</div><h1>${['Antes de começar','Sua rotina e seu cuidado','O que importa para você'][assessmentStep-1]}</h1><p>A equipe revisa suas respostas. Elas não dizem, sozinhas, se você pode treinar.</p><form id="assessment">${assessmentStep===1?field('newSymptoms','Teve algum sintoma novo ou diferente nas últimas semanas?','select',[['sim','Sim'],['nao','Não'],['nao_sei','Não sei']])+field('duration','Há quanto tempo sente dor lombar?','select',[['Menos de 3 meses','Menos de 3 meses'],['3 meses ou mais','3 meses ou mais'],['Não sei','Não sei']])+field('symptoms','O que mudou ou gostaria de contar? (opcional)'):assessmentStep===2?field('care','Que cuidados ou tratamentos você já faz? (opcional)')+field('preference','Há orientação profissional, adaptação ou preferência que devemos considerar? (opcional)'):field('goal','Qual atividade você gostaria de retomar?')+field('function','Como está essa atividade hoje? (opcional)')}<p class="muted">Sintomas novos ou preocupantes? Fale com a equipe antes de continuar.</p><button class="full">${assessmentStep<3?'Continuar':'Enviar para a equipe'}</button>${assessmentStep>1?btn('Voltar','assessment-back','secondary'):''}</form></div>`}
function goalText(){const r=me.records.find(r=>r.kind==='triage');return r?JSON.parse(r.payload).goal||'Sua atividade escolhida':'Sua atividade escolhida'}
function careResponseForm(id,sid){return `<form id="${id}" data-id="${sid}"><label for="pain">Dor agora (0 = nenhuma, 10 = máxima)</label><input name="pain" id="pain" type="number" min="0" max="10" required>${id==='complete'||id==='lesson-checkout'?'<label for="effort">Esforço percebido (0 = nenhum, 10 = máximo)</label><input id="effort" name="effort" type="number" min="0" max="10" required>':''}<label for="newSymptoms">Sintoma novo ou diferente?</label><select id="newSymptoms" name="newSymptoms" required><option value="">Selecione</option><option value="nao">Não</option><option value="sim">Sim</option><option value="nao_sei">Não sei</option></select><label for="function">Atividade escolhida: ${esc(goalText())}</label><textarea id="function" name="function" maxlength="1000" placeholder="Como ficou essa atividade? (opcional)"></textarea><label for="notes">Quer contar algo? (opcional)</label><textarea id="notes" name="notes" maxlength="2000"></textarea><button class="full">Salvar registro</button>${btn('Pular — não respondi','skip-'+id,'secondary')}</form>`}
function careCheckout(){return `<div class="card form checkout"><span class="eyebrow">Depois da sessão</span><h1>Como você está agora?</h1><p>Seu relato ajuda a equipe a acompanhar sua resposta.</p>${careResponseForm('lesson-checkout',journey.ongoing)}</div>`}
function careRecord(r){const p=JSON.parse(r.payload);const missing=p.response==='missing';const labels={triage:'Avaliação inicial',triage_draft:'Avaliação em rascunho',consent:'Consentimento',session:'Depois da sessão',followup:'Dia seguinte',review:'Retorno da equipe',event:'Evento relatado',between:'Dia entre sessões',message:'Mensagem',pause:'Pausa'};return `<article class="record ${missing?'missing-record':''}"><div class="row"><strong>${esc(labels[r.kind]||r.kind)}</strong><small>${date(r.created)}</small></div>${missing?'<p class="missing-label">◌ Não respondi · sintomas desconhecidos</p>':`<p>${p.pain!==undefined&&p.pain!==null?'Dor agora: '+esc(p.pain)+'/10. ':''}${p.effort!==undefined&&p.effort!==null?'Esforço: '+esc(p.effort)+(typeof p.effort==='number'?'/10':'')+'. ':''}${esc(p.notes||p.goal||p.activity||p.purpose||'Registro recebido.')}</p>`}${p.newSymptoms?`<p class="muted">Sintoma novo: ${esc({sim:'sim',nao:'não',nao_sei:'não sei'}[p.newSymptoms]||'não informado')}</p>`:''}${p.function?`<p>Atividade: ${esc(p.function)}</p>`:''}</article>`}
function responseChart(kind,title){const rs=me.records.filter(r=>r.kind===kind).slice(0,8).reverse();return `<div class="card chart-card"><h2>${title}</h2><p class="muted">Dor no momento do registro · escala 0–10</p><div class="response-bars">${rs.map(r=>{const p=JSON.parse(r.payload);return `<div class="bar-item"><div class="bar-space">${p.pain===null||p.response==='missing'?'<span class="missing-point">◌</span>':`<div class="response-bar height-${Math.round(p.pain)}"></div><strong>${esc(p.pain)}</strong>`}</div><small>${new Date(r.created*1000).toLocaleDateString('pt-BR')}</small></div>`}).join('')||'<p>Sem registros ainda.</p>'}</div><p class="muted">◌ = não respondi. Não representa ausência de sintomas.</p></div>`}
function careHistory(){const filters={adherence:['session','between'],response:['session','followup'],events:['event','pause']};const records=me.records.filter(r=>filters[historyTab].includes(r.kind));const last=me.sessions[0];return `<span class="eyebrow">Sua trajetória</span><h1>Histórico</h1><div class="history-tabs" role="group" aria-label="Tipo de histórico">${[['adherence','Adesão'],['response','Resposta'],['events','Eventos']].map(([v,l])=>btn(l,'history-'+v,historyTab===v?'':'secondary')).join('')}</div>${historyTab==='response'?`<div class="grid">${responseChart('session','Depois da sessão')}${responseChart('followup','Dia seguinte')}</div>`:''}<div class="grid"><section class="card"><h2>${{adherence:'O que você realizou',response:'Como você respondeu',events:'Eventos e pausas'}[historyTab]}</h2>${records.map(careRecord).join('')||'<p>Seus registros aparecerão aqui.</p>'}</section><aside class="card"><h2>Dia seguinte</h2>${last?.completed&&!last.followup?`<p>Disponível em ${date(last.completed+86400)}.</p>${Date.now()/1000>=last.completed+86400?careResponseForm('followup',last.id):'<p>Enquanto isso, contato e pausa continuam disponíveis.</p>'}`:'<p>Nenhum acompanhamento pendente.</p>'}${btn('Compartilhar uma mensagem com a equipe','help','secondary')}</aside></div>`}
function between(){return `<div class="card form"><span class="eyebrow">Entre um encontro e outro</span><h1>Dia entre sessões</h1><p>Descanso ou atividade leve, conforme sua rotina e orientação. Não há uma meta de tempo universal.</p>${me.betweenInstruction?`<div class="focus-content"><strong>Orientação da equipe</strong><p>${esc(me.betweenInstruction)}</p></div>`:''}<form id="between"><label for="activity">Como foi seu dia?</label><select id="activity" name="activity"><option value="descanso">Descanso</option><option value="caminhada">Caminhada</option><option value="bicicleta">Bicicleta</option><option value="outra">Outra atividade</option></select><label for="notes">Quer registrar algo? (opcional)</label><textarea id="notes" name="notes" maxlength="2000"></textarea><button class="full">Registrar o dia</button></form></div>`}
function review(){const rs=me.records.filter(r=>r.kind==='review'||r.kind==='message');return `<div class="card form"><span class="eyebrow">Retorno da equipe</span><h1>Seu próximo passo, com orientação.</h1><p>Avanços e ajustes são decididos pelo profissional com base na sua resposta, execução e preferência.</p>${rs.map(careRecord).join('')||'<p>Sua equipe ainda não registrou um retorno.</p>'}${btn('Responder à equipe','help','secondary')}</div>`}
function careHelp(){return `<span class="eyebrow">Estamos atentos ao seu ritmo</span><h1>Falar com a equipe</h1><p>Sintomas novos, piora que não passa ou algo preocupante: procure avaliação. Em emergência, ligue 192 (SAMU).</p><div class="grid"><section class="card"><h2>Enviar mensagem</h2><p>Mensagens ficam no painel local da equipe. Este piloto não envia alertas e não é um canal de urgência.</p><form id="message"><label for="message-notes">Sua mensagem</label><textarea id="message-notes" name="notes" required minlength="3" maxlength="2000"></textarea><button class="full">Enviar à equipe</button></form>${me.records.filter(r=>r.kind==='message').slice(0,5).map(careRecord).join('')}</section><aside class="card"><h2>Interromper e relatar</h2><p>Um evento novo pode ser registrado aqui. O programa será pausado para revisão.</p><form id="event"><label for="event-notes">O que aconteceu?</label><textarea id="event-notes" name="notes" required minlength="3" maxlength="2000"></textarea><button class="full danger">Registrar evento e pausar</button></form></aside></div><p class="muted">Este aplicativo não substitui avaliação profissional. O roteiro detalhado de urgência deve ser definido pela equipe clínica.</p>`}
function pauseConfirm(){return `<div class="card form"><span class="eyebrow">Você pode pausar</span><h1>Quer pausar o programa?</h1><p>Novas sessões ficarão suspensas. Seus registros permanecem disponíveis e a equipe poderá revisar a retomada.</p>${btn('Pausar meu programa','pause-confirm')}${btn('Voltar','dashboard','secondary')}</div>`}
async function careAction(a){if(a==='theme'){document.documentElement.dataset.theme=document.documentElement.dataset.theme==='dark'?'light':'dark';localStorage.setItem('care-theme',document.documentElement.dataset.theme);return true}if(a==='font'){document.documentElement.dataset.large=document.documentElement.dataset.large==='true'?'false':'true';localStorage.setItem('care-large',document.documentElement.dataset.large);return true}
if(a==='triage'){const draft=me.records.find(r=>r.kind==='triage_draft');assessmentDraft=draft?JSON.parse(draft.payload):{};assessmentStep=1;page='triage';render();return true}
if(a==='assessment-save'){const f=document.querySelector('#assessment');Object.assign(assessmentDraft,Object.fromEntries(new FormData(f)));await api('triage/draft',assessmentDraft);me=await api('me');page='dashboard';notice('Rascunho salvo. Você pode continuar depois.');render();return true}
if(a==='assessment-back'){assessmentStep--;render();return true}
if(a==='pause-request'){page='pauseConfirm';render();return true}if(a==='pause-confirm'){await api('pause',{});me=await api('me');page='dashboard';render();notice('Programa pausado. Sua equipe revisará a retomada.');return true}
if(a.startsWith('history-')){historyTab=a.slice(8);page='diary';render();return true}
if(a.startsWith('skip-')){const id=a.slice(5);const sid=id==='lesson-checkout'?journey.ongoing:Number(document.querySelector('#'+id).dataset.id);await api('session/'+(id==='followup'?'followup':'complete'),{id:sid,skipped:true});me=await api('me');if(id==='lesson-checkout'){journey=await api('protocol');page='celebrate'}else page='diary';render();return true}
if(['between','review'].includes(a)){page=a;render();return true}return false}
async function careSubmit(f,d){if(f.id==='assessment'){Object.assign(assessmentDraft,d);if(assessmentStep<3){assessmentStep++;render()}else{await api('triage',assessmentDraft);me=await api('me');page='dashboard';notice('Avaliação enviada para a equipe.');render()}return true}
if(f.id==='between'||f.id==='message'||f.id.startsWith('reply-')){if(f.id.startsWith('reply-'))d.id=Number(f.dataset.id);await api(f.id==='between'?'between':'message',d);me=await api('me');if(f.id.startsWith('reply-'))patients=await api('patients');notice(f.id==='between'?'Dia registrado.':'Mensagem registrada no painel da equipe.');render();return true}
if(['lesson-checkout','complete','followup'].includes(f.id)){d.id=f.id==='lesson-checkout'?journey.ongoing:Number(f.dataset.id);d.pain=Number(d.pain);if(d.effort!==undefined)d.effort=Number(d.effort);await api('session/'+(f.id==='followup'?'followup':'complete'),d);me=await api('me');if(f.id==='lesson-checkout'){journey=await api('protocol');page='celebrate'}else page='diary';render();return true}return false}
