let evaluations=[];
const evaluationItems=[
  ['scope','Público e escopo','Adultos com dor lombar subaguda ou crônica inespecífica; indicação individual depende da avaliação profissional.'],
  ['triage','Entrada e exclusão','A pessoa relata sintomas e objetivo. A equipe precisa definir e registrar critérios formais antes do piloto real.'],
  ['safety','Pausa e encaminhamento','Relato de evento suspende aulas. O canal no app não é de urgência e não envia alerta externo.'],
  ['sessions','Aulas e progressão','Há módulos e política individual, mas a sequência de nove sessões e os vídeos aguardam aprovação.'],
  ['followup','Resposta e adesão','Dor 0–10, esforço, sintomas novos, atividade e registro de 24 horas são separados de adesão. Falta de resposta volta à revisão.'],
  ['evidence','Evidência e linguagem','As referências orientam componentes do cuidado; os limites operacionais e o produto completo não estão validados como intervenção.'],
  ['pilot','Piloto assistido','Primeiro caso fictício completo; depois participante real apenas com conteúdo, privacidade, suporte e infraestrutura aprovados.']
];
function medicalGuide(){const latest=new Map();for(const e of evaluations)if(!latest.has(e.item))latest.set(e.item,e);return `<span class="eyebrow">Avaliação profissional do produto</span><h1>O que o Dr. está avaliando</h1><p>Esta área reúne a jornada e permite registrar um parecer por item. Um parecer sobre a interface não substitui decisão clínica individual nem valida a eficácia do produto.</p><div class="cards"><article class="card"><h2>1. Entrada</h2><p>Cadastro → avaliação em três passos → atribuição → revisão. A ausência de sintomas relatados não libera aulas automaticamente.</p></article><article class="card"><h2>2. Orientação</h2><p>O profissional registra plano e conteúdo individuais. O check-in prepara uma versão de manutenção ou proteção conforme limites autorais.</p></article><article class="card"><h2>3. Resposta</h2><p>Após a aula e no dia seguinte, a pessoa registra sua resposta. Evento novo suspende sessões; resposta ausente exige nova revisão.</p></article></div><div class="card"><h2>Caso demonstrativo fictício</h2><ol><li>“Participante A” informa dor lombar há mais de três meses e objetivo de voltar a subir escadas.</li><li>A equipe lê a triagem, registra uma decisão justificada e prepara uma sessão individual.</li><li>A pessoa faz o check-in, vê sua aula, pode pausar e registra dor, esforço e função.</li><li>Após 24 horas, informa a resposta ou marca dado ausente. A equipe revisa o caso antes da próxima etapa quando necessário.</li></ol><p class="muted">Este exemplo mostra o fluxo; não é um caso clínico, resultado ou depoimento real.</p></div><div class="card"><h2>Limites da evidência</h2><p>Exercício e acompanhamento profissional têm literatura própria. A eficácia desta sequência específica, seus limites numéricos, as nove sessões e a experiência digital completa ainda precisam ser avaliados separadamente. As referências do dossiê não devem ser apresentadas como validação do infoproduto.</p></div><h2>Parecer por item</h2>${evaluationItems.map(([id,title,description])=>{const e=latest.get(id);return `<details class="card patient-case"><summary>${esc(title)} · ${e?esc({approved:'aprovado',adjust:'ajustar',pending:'pendente'}[e.status]):'sem parecer'}</summary><p>${esc(description)}</p>${e?`<p><strong>Último parecer:</strong> ${esc(e.notes)} <small>${date(e.created)}</small></p>`:''}<form id="evaluation-${id}" data-item="${id}"><label>Classificação<select name="status" required><option value="pending">Pendente</option><option value="adjust">Ajustar</option><option value="approved">Aprovado neste item</option></select></label><label>Motivo e condição para aprovação<textarea name="notes" required minlength="5" maxlength="2000"></textarea></label><button class="full">Registrar parecer</button></form></details>`}).join('')}`}
async function medicalAction(a){if(a==='evaluation'){evaluations=await api('evaluation');page='evaluation';render();return true}return false}
async function medicalSubmit(f,d){if(!f.id.startsWith('evaluation-'))return false;await api('evaluation',{item:f.dataset.item,status:d.status,notes:d.notes});evaluations=await api('evaluation');notice('Parecer registrado.');render();return true}
function bindMedicalReview(){app.querySelectorAll('form[id^="review-"]').forEach(f=>{const label=document.createElement('label');label.className='check';label.innerHTML='<input name="reviewed" type="checkbox"> Para ativar, confirmo que revisei as respostas disponíveis, os sintomas novos relatados e a necessidade de avaliação presencial.';f.insertBefore(label,f.querySelector('button.full'));const p=patients.find(x=>x.id===Number(f.dataset.id));const triage=p?.records.find(x=>x.kind==='triage');const data=triage?JSON.parse(triage.payload):null;if(p?.pendingRisk){const warning=document.createElement('p');warning.className='missing-record';warning.textContent='Prioridade de revisão: a triagem relata preocupação neurológica ou outra condição séria. Confira as respostas e o encaminhamento.';f.closest('.patient-case')?.insertBefore(warning,f)}if(data?.urgentConcern||data?.seriousCondition==='sim'){const urgent=document.createElement('label');urgent.className='check';urgent.innerHTML='<input name="urgentAssessed" type="checkbox"> Para ativar este caso, confirmo que a preocupação relatada foi avaliada clinicamente e descrevi o resultado na justificativa.';f.insertBefore(urgent,f.querySelector('button.full'))}})}
function appendEvidenceSources(){if(page!=='evaluation')return;const section=document.createElement('section');section.className='card';section.innerHTML='<h2>Fontes para revisar o escopo</h2><p><a href="https://www.acponline.org/sites/default/files/acp-policy-library/guidelines/noninvasive_treatments_for_chronic_low_back_pain_2017.pdf" target="_blank" rel="noopener noreferrer">ACP 2017 — diretriz de tratamentos não invasivos</a></p><p><a href="https://www.nice.org.uk/guidance/NG59/chapter/recommendations" target="_blank" rel="noopener noreferrer">NICE NG59 — avaliação e manejo de lombalgia</a></p><p><a href="https://www.nice.org.uk/guidance/ng127/chapter/recommendations-for-adults-aged-over-16" target="_blank" rel="noopener noreferrer">NICE NG127 — reconhecimento e encaminhamento neurológico</a></p><p class="muted">Essas fontes não validam a sequência específica, os limites numéricos nem o aplicativo. As demais referências do dossiê ainda exigem auditoria do texto completo.</p>';app.querySelector('main')?.append(section)}
