let journey=null, stepIndex=0, focusPaused=false, focusRemaining=0, challengeAccepted=false;
const modes={protection:['🔵','Cuidado ativo','Vamos respeitar seu momento e seguir uma versão mais suave.'],maintenance:['🟢','Seu ritmo de hoje','Sua aula está preparada. Um passo de cada vez.'],advance:['✨','Desafio autorizado','Hoje você tem um desafio opcional preparado pela sua equipe.']};
const modeTag=()=>{const m=modes[journey?.lesson?.mode]||modes.maintenance;return `<span class="pill mode-${esc(journey?.lesson?.mode)}">${m[0]} ${m[1]}</span>`};
function choices(name,items){return `<div class="choices">${items.map(([value,label])=>`<label class="choice"><input type="radio" name="${name}" value="${value}" required><span>${label}</span></label>`).join('')}</div>`}
function protocol(){if(!journey)return '<p>Carregando sua jornada…</p>';const current=journey.modules.find(m=>m.id===journey.module);const total=Object.values(journey.progress).reduce((a,b)=>a+b,0);const last=me.sessions[0];
return `<div class="row"><div><span class="eyebrow">Seu cuidado em movimento</span><h1>Minha jornada</h1><p>Não precisa correr. Cada etapa tem seu momento.</p></div><span class="pill">${total} ${total===1?'sessão concluída':'sessões concluídas'}</span></div><div class="protocol-grid"><section><div class="journey-track">${journey.modules.map(m=>{const locked=m.id>journey.module;const count=journey.progress[m.id]||0;return `<article class="module ${locked?'locked':m.id===journey.module?'current':''}"><div class="module-number">${locked?'🔒':m.id<journey.module?'✓':m.id}</div><div><span class="eyebrow">${m.weeks}</span><h2>${m.name}</h2><p>${locked?'Seu próximo capítulo. A equipe acompanha a passagem de etapa.':`${count} ${count===1?'sessão registrada':'sessões registradas'} nesta etapa`}</p>${m.id===journey.module&&journey.targetSessions?`<progress max="${journey.targetSessions}" value="${Math.min(count,journey.targetSessions)}" aria-label="Sessões concluídas nesta etapa"></progress><small>${count}/${journey.targetSessions} sessões · referência de acompanhamento</small>`:''}</div></article>`}).join('')}</div><p class="muted">As semanas orientam a jornada. A passagem de módulo é acompanhada pela sua equipe.</p></section><aside class="card daily-card"><span class="eyebrow">A aula de hoje</span><h2>${current.name}</h2>${journey.ongoing?`<p>Sua sessão está em andamento. Podemos continuar de onde você parou.</p>${btn('Retomar Modo Foco →','lesson-resume')}`:!journey.active||!journey.configured?`<div class="soft-icon">🌱</div><p>Sua equipe está preparando a orientação individual. Você já pode conhecer a trilha.</p>${btn('Ver minha triagem','triage','secondary')}`:last?.completed&&!last.followup?`<p>Antes da próxima aula, vamos registrar como você ficou depois da última sessão.</p><p class="muted">Disponível em ${date(last.completed+86400)}</p>${btn('Ver acompanhamento','diary')}`:!journey.calibrated?checkinForm():`<p>${modes[journey.lesson.mode][2]}</p>${modeTag()}<p>${btn('Ver minha aula →','lesson')}</p>${btn('Atualizar como estou','recalibrate','secondary')}`}</aside></div>`}
function checkinForm(){return `<p>Como você está hoje? Três respostas para preparar sua aula.</p><form id="checkin"><fieldset><legend>☀️ Dor nesta manhã</legend>${choices('pain',Array.from({length:11},(_,i)=>[i,i]))}<small>0 = nenhuma · 10 = máxima</small></fieldset><fieldset><legend>🌙 Como você dormiu?</legend>${choices('sleep',[[1,'😴 Mal'],[2,'🙂 Regular'],[3,'😊 Bem']])}</fieldset><fieldset><legend>🍃 Como está sua mente?</legend>${choices('stress',[[1,'😊 Tranquila'],[2,'😐 Cansada'],[3,'😣 Sobrecarregada']])}</fieldset><button class="full">Preparar minha aula →</button></form><p class="muted">Se algo mudou ou preocupa você, pode pausar e pedir ajuda.</p>${btn('Preciso de ajuda','help','secondary')}`}
function lesson(){if(!journey?.lesson)return protocol();const l=journey.lesson;const n=me.sessions.filter(s=>s.completed).length+1;return `<div class="row"><div><span class="eyebrow">${journey.modules[l.module-1].name}</span><h1>Sessão ${n}</h1></div>${modeTag()}</div><p>${modes[l.mode][2]}</p><div class="grid"><section>${l.blocks.map((block,i)=>`<article class="card lesson-block"><span class="eyebrow">${i===2?'Opcional · preparado para você':'Bloco '+(i+1)}</span><h2>${block.name}</h2>${block.steps.map(s=>`<div class="exercise-row"><div class="play-badge">${s.video?'▶':'◷'}</div><div><h3>${esc(s.title)}</h3><p>${esc(s.instruction)}</p>${s.objective?`<p><strong>Objetivo:</strong> ${esc(s.objective)}</p>`:''}${s.version?`<p><strong>Versão indicada:</strong> ${esc(s.version)}</p>`:''}${s.alternative?`<p><strong>Alternativa:</strong> ${esc(s.alternative)}</p>`:''}<small>Tempo sugerido pelo programa: ${s.seconds<60?s.seconds+' s':Math.round(s.seconds/60*10)/10+' min'} ${s.video?'· com vídeo':'· orientação guiada'}</small></div></div>`).join('')}</article>`).join('')}</section><aside class="card daily-card"><div class="soft-icon">▶</div><h2>Agora, só você e sua aula.</h2><p>Acompanhe uma etapa por vez, com pausa sempre disponível.</p>${btn('Iniciar Modo Foco','lesson-start')}<p>${btn('Voltar à jornada','protocol','secondary')}</p></aside></div>`}
function focusSteps(){return journey.lesson.blocks.flatMap((b,i)=>b.steps.map(s=>({...s,block:b.name,optional:i===2})))}
function lessonFocus(){const steps=focusSteps(),s=steps[stepIndex];if(!s)return careCheckout();return `<div class="focus lesson-focus"><div class="row"><span class="eyebrow">${esc(s.block)} · ${stepIndex+1}/${steps.length}</span>${btn('Tela cheia','fullscreen','secondary')}${btn('Sair do modo foco','lesson','secondary')}</div><h1>${esc(s.title)}</h1><div class="video-stage">${s.video?`<video id="lesson-video" controls playsinline preload="metadata" src="${esc(s.video)}"></video>`:`<div class="breathing-orb">${s.optional?'✦':'◯'}</div><p>Orientação guiada</p>`}</div><p class="focus-instruction">${esc(s.instruction)}</p>${s.objective?`<p><strong>Objetivo:</strong> ${esc(s.objective)}</p>`:''}${s.version?`<p><strong>Versão indicada:</strong> ${esc(s.version)}</p>`:''}${s.alternative?`<p><strong>Alternativa:</strong> ${esc(s.alternative)}</p>`:''}<p class="muted">Pare e fale com a equipe se surgir dor diferente da habitual, formigamento ou fraqueza.</p><div class="timer" id="step-timer">${formatTime(focusRemaining)}</div><div class="focus-controls">${btn('Anterior','step-prev','secondary')}${btn(s.optional&&!challengeAccepted?'Quero fazer o desafio':focusPaused?'Continuar':'Pausar','step-pause')}${btn(stepIndex===steps.length-1?'Finalizar aula':'Próxima etapa','step-next','secondary')}${s.optional?btn('Pular desafio','skip-challenge','secondary'):''}</div><p class="muted">Você pode interromper a qualquer momento.</p>${btn('Interromper e pedir ajuda','help','secondary')}</div>`}
function formatTime(n){return `${Math.floor(n/60).toString().padStart(2,'0')}:${(n%60).toString().padStart(2,'0')}`}
function checkout(){return `<div class="card form checkout"><span class="eyebrow">Um último cuidado</span><h1>Como foi para você?</h1><p>Seu relato ajuda a preparar o próximo encontro.</p><form id="lesson-checkout"><fieldset><legend>Como sentiu o esforço?</legend>${choices('effort',[['leve','🍃 Leve'],['moderado','🌿 Moderado'],['dificil','🌳 Difícil']])}</fieldset><label for="pain">Dor agora, de 0 a 10</label><input id="pain" name="pain" type="number" min="0" max="10" step="1" required><label for="notes">Quer contar algo? (opcional)</label><textarea id="notes" name="notes" maxlength="2000"></textarea><button class="full">Concluir meu registro</button></form><p class="muted">Escolha a opção que melhor descreve sua experiência de hoje.</p></div>`}
function celebrate(){const count=journey?.progress?.[journey.module]||0;return `<div class="card form celebration"><div class="celebration-icon">✓</div><span class="eyebrow">Um passo importante</span><h1>Você cuidou de você hoje.</h1><p>Sessão registrada. Sua jornada se constrói com constância e respeito ao seu ritmo.</p>${journey?.targetSessions?`<progress max="${journey.targetSessions}" value="${Math.min(count,journey.targetSessions)}" aria-label="Progresso do módulo"></progress><p>${count}/${journey.targetSessions} sessões nesta etapa</p>`:''}<p>Amanhã, depois de 24 horas, vamos acompanhar como você ficou.</p>${btn('Ver minha jornada','protocol')}<p>${btn('Abrir meu diário','diary','secondary')}</p></div>`}
async function protocolAction(a){if(a==='fullscreen'){try{await document.querySelector('.lesson-focus').requestFullscreen();if(screen.orientation?.lock)await screen.orientation.lock('landscape')}catch{notice('Se preferir, gire seu dispositivo para acompanhar a aula.')}return true}if(!['protocol','lesson','lesson-start','lesson-resume','recalibrate','step-next','step-prev','step-pause','skip-challenge'].includes(a))return false;
if(a==='protocol'){journey=await api('protocol');page='protocol'}
else if(a==='lesson'){page='lesson';if(document.fullscreenElement)await document.exitFullscreen()}
else if(a==='recalibrate'){journey.calibrated=false;page='protocol'}
else if(a==='lesson-start'||a==='lesson-resume'){if(!journey.ongoing){await api('session/start',{});me=await api('me');journey=await api('protocol')}const saved=JSON.parse(sessionStorage.getItem('focus-'+me.id+'-'+journey.ongoing)||'null');stepIndex=saved&&Number.isInteger(saved.index)&&saved.index>=0&&saved.index<focusSteps().length?saved.index:0;challengeAccepted=false;focusPaused=false;focusRemaining=saved&&Number.isInteger(saved.remaining)&&saved.remaining>=0&&saved.remaining<=focusSteps()[stepIndex].seconds?saved.remaining:focusSteps()[stepIndex].seconds;page='lessonFocus'}
else if(a==='step-pause'){if(focusSteps()[stepIndex].optional)challengeAccepted=true;focusPaused=!focusPaused;const video=document.querySelector('#lesson-video');if(video){if(focusPaused)video.pause();else video.play().catch(()=>{})}document.querySelector('[data-action="step-pause"]').textContent=focusPaused?'Continuar':'Pausar';return true}
else if(a==='step-prev'){stepIndex=Math.max(0,stepIndex-1);focusRemaining=focusSteps()[stepIndex].seconds;focusPaused=false}
else if(a==='skip-challenge'){page='checkout';if(document.fullscreenElement)await document.exitFullscreen()}
else {stepIndex++;if(stepIndex>=focusSteps().length){page='checkout';if(document.fullscreenElement)await document.exitFullscreen()}else{focusRemaining=focusSteps()[stepIndex].seconds;focusPaused=false}}
if(page==='lessonFocus'&&focusSteps()[stepIndex]?.optional&&!challengeAccepted)focusPaused=true;render();return true}
function bindProtocol(){if(page!=='lessonFocus')return;const video=document.querySelector('#lesson-video');if(video){if(!focusPaused)video.play().catch(()=>{});video.onended=()=>action('step-next');video.onerror=()=>notice('Vídeo indisponível. Use a orientação escrita ou pause e contate sua equipe.');}
timer=setInterval(()=>{sessionStorage.setItem('focus-'+me.id+'-'+journey.ongoing,JSON.stringify({index:stepIndex,remaining:focusRemaining}));if(focusPaused){if(video&&!video.paused)video.pause();return}if(focusRemaining>0)focusRemaining--;const el=document.querySelector('#step-timer');if(el)el.textContent=formatTime(focusRemaining);if(!video&&focusRemaining===0)action('step-next')},1000)}
async function protocolSubmit(f,d){if(f.id==='checkin'){await api('checkin',{pain:Number(d.pain),sleep:Number(d.sleep),stress:Number(d.stress)});journey=await api('protocol');page='protocol';render();return true}if(f.id==='lesson-checkout'){await api('session/complete',{id:journey.ongoing,pain:Number(d.pain),effort:d.effort,notes:d.notes});me=await api('me');journey=await api('protocol');page='celebrate';render();return true}if(f.id.startsWith('policy-')){await api('policy',{id:Number(f.dataset.id),config:JSON.parse(d.config)});notice('Política individual salva. A próxima aula exigirá nova calibração.');page='team';render();return true}return false}
function policyEditor(p){return `<details class="policy-editor"><summary>Configurar jornada e variações individuais</summary><p>Política autoral, sem validação clínica do Sink Score. Módulo é liberado por decisão profissional; as respostas só selecionam conteúdo previamente autorizado. Leve/Moderado/Difícil são categorias autorais de esforço.</p><form id="policy-${p.id}" data-id="${p.id}"><label>Configuração individual (JSON)<textarea name="config" required spellcheck="false" rows="12" placeholder="Cole a configuração conforme docs/06-protocolo-aulas.md">${esc(p.policy?JSON.stringify(p.policy,null,2):'')}</textarea></label><button class="full">Salvar política individual</button></form></details>`}
